#!/usr/bin/env python3

'''
Generate wireguard config files.

See: https://www.wireguardconfig.com

'''

import pathlib
import subprocess
import toml

CONFIG = toml.load(pathlib.Path(__file__).parent / 'config.toml')
LAN = CONFIG['LAN']
HOSTS = CONFIG['host']

def get_gateway():
  gw = HOSTS[LAN['gateway']]
  wg_conf = {}
  wg_conf |= CONFIG['peer_defaults']
  wg_conf |= dict(
    Endpoint = gw['Endpoint'],
    PublicKey = gw['PublicKey'],
    AllowedIPs = f'{LAN["PREFIX"]}0/{LAN["MASK"]}',
  )
  return wg_conf


def get_pubkey(config):
  if pubkey := config.get('PublicKey'):
    return pubkey
  if privkey := config.get('PrivateKey'):
    return subprocess.check_output(['wg', 'pubkey'], input=privkey, encoding='ascii').strip()
  raise ValueError('no keys')


def get_addr(octet):
  return f'{LAN["PREFIX"]}{octet}'


def get_config_for_host(host):
  config = HOSTS[host]

  wg_conf = [('Interface', interface := {})]
  interface |= CONFIG['interface_defaults']
  interface['PrivateKey'] = config['PrivateKey']

  if config.pop('is_gateway', False):
    for name, peer in HOSTS.items():
      wg_conf.append(('Peer', wg_peer := {}))
      wg_peer['# Host'] = name
      wg_peer |= CONFIG['peer_defaults']
      wg_peer |= dict(
        AllowedIPs = f'{get_addr(peer["Address"])}/32',
        PublicKey = get_pubkey(peer),
      )

  else:
    wg_conf.append(('Peer', get_gateway()))

  if config.get('is_linux'):
    pass
  else: # windows
    interface['Address'] = f'{get_addr(config["Address"])}/{LAN["MASK"]}'
    interface['DNS'] = ', '.join(LAN['DNS'])


  return wg_conf



def get_script_for_host(host):
  config = HOSTS[host]
  addr = f'{get_addr(config["Address"])}/{LAN["MASK"]}'
  wan = config.get("wan_interface")

  script = f'''#!/bin/bash

# autogenerated up script for {host}

set -e
set -u
set -o pipefail
set -x

sudo ip link set down dev wg0 || true
sudo ip link del dev wg0 || true
'''

  if config.get('is_gateway'):
    script += f'''
sudo iptables -D FORWARD -i wg0 -j ACCEPT || true
sudo iptables -D POSTROUTING -o {wan} -j MASQUERADE -t nat || true
'''

  script += f'''
ip link add dev wg0 type wireguard
wg setconf wg0 /etc/wireguard/wg0.conf
ip address add dev wg0 {addr}
ip link set up dev wg0
'''

  if config.get('is_gateway'):
    script += f'''
sysctl -w net.ipv4.ip_forward=1
iptables -A FORWARD -i wg0 -j ACCEPT
iptables -A POSTROUTING -o {wan} -j MASQUERADE -t nat
'''
  return script

def print_config(config):
  for heading, section in config:
    print(f'[{heading}]')
    for key, value in section.items():
      print(f'{key:<20} = {value}')
    print('')


def main(args):

  if args.type == 'conf':
    config = get_config_for_host(args.host)
    print_config(config)
    return
  if args.type == 'script':
    script = get_script_for_host(args.host)
    print(script)
    return
  raise ValueError(f'unknown type {args.type}')


if __name__ == '__main__':
  import argparse
  parser = argparse.ArgumentParser(argparse.RawTextHelpFormatter, description=__doc__)
  parser.add_argument('--host')
  parser.add_argument('--type', default='conf')
  main(parser.parse_args())
