#!/usr/bin/env python3

import sys
import json

from pygments import highlight
from pygments.lexers import JsonLexer
from pygments.formatters import Terminal256Formatter

data = json.loads(sys.stdin.read())
pp = json.dumps(data, indent=2)

print(highlight(pp, JsonLexer(), Terminal256Formatter()))
